stages:
  - test
  - deploy

build_job:
  stage: test
  tags:
    - test  # test 태그가 설정된 Runner를 사용
  script:
    - echo "Building and testing application..."
    - chmod +x gradlew
    - ./gradlew -x test clean build
    - cd bin/libs
    - java -jar -Dspring.profiles=prod aurasphere-0.0.1-SNAPSHOT.jar
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
    - docker build -t aurasphere-backend-server:latest .
    - docker tag aurasphere-backend-server:latest seungilbaek/aurasphere-server:latest
    - docker push seungilbaek/aurasphere-server:latest
    - echo "Build and test completed successfully."

deploy_job:
  stage: deploy
  tags:
    - deploy  # deploy 태그가 설정된 Runner를 사용
  script:
    - echo "Deploying application..."
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d
