stages:
  - prebuild
  - build
  - deploy

prebuild:
  stage: prebuild
  tags:
    - test
  script:
    - chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar

build_job:
  stage: build
  tags:
    - test  # test 태그가 설정된 Runner를 사용
  script:
    - echo "Building and testing application..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
    - docker build -t "$DOCKER_USERNAME"/aurasphere-server:latest .
    - docker push "$DOCKER_USERNAME"/aurasphere-server:latest
    - echo "Build and push completed successfully."



deploy_job:
  stage: deploy
  tags:
    - deploy  # deploy 태그가 설정된 Runner를 사용
  script:
    - echo "Deploying application..."
    - docker-compose down
    - docker-compose up -d
