stages:
  - prebuild
  - build
  - deploy

variables:
  ENV_COPY_PATH: .env

prebuild:
  stage: prebuild
  tags:
    - test
  script:
    - cat ${ENV_FILE} > ${ENV_COPY_PATH}
    - sudo chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar
      - ${ENV_COPY_PATH}
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

build_job:
  stage: build
  tags:
    - test  # test 태그가 설정된 Runner를 사용
  script:
    - echo "Building and testing application..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" https://index.docker.io/v1/
    - docker build -t "$DOCKER_USERNAME"/aurasphere-server:latest .
    - docker push "$DOCKER_USERNAME"/aurasphere-server:latest
    - echo "Build and push completed successfully."
  artifacts:
    paths:
      - ${ENV_COPY_PATH}
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

deploy_job:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Deploying application..."
    - echo "envfile ${ENV_FILE}"
    - docker compose --env-file ${ENV_COPY_PATH} down
    - docker compose --env-file ${ENV_COPY_PATH} pull
    - docker compose --env-file ${ENV_COPY_PATH} up -d
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'