stages:
  - build
  - package
  - deploy

build: # JOB 이름
  image: gradle:8.11.1-jdk17
  stage: build
  script:
    - echo [INFO] YML Settings
    - cd ./src/main/resources
    - echo "$APPLICATION_YML" > "application.yml" # gitlab APPLICATION_YML을 이용하여 application.yml 파일 생성
    - echo [INFO] spring-boot project build
    - cd ../../..
    - chmod +x gradlew
    - ./gradlew clean
    - ./gradlew bootjar
  tags:
    - build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  only:
    - feature/notification

package:
  image: docker:latest
  stage: package
  services:
    - name: docker:dind
      command: ["--iptables=false", "--tls=false", "--host=tcp://0.0.0.0:2375", "--insecure-registry=0.0.0.0/0"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - if [ -z "$DOCKER_HUB_NAME" ] || [ -z "$DOCKER_HUB_PW" ]; then echo "Docker Hub credentials are missing"; exit 1; fi
    - echo "$DOCKER_HUB_PW" | docker login --username "$DOCKER_HUB_NAME" --password-stdin
    - echo "Docker Hub 로그인 성공"
  script:
    - echo "$DOTENV_FILE" > .env
    - cat .env
    - docker-compose up -d
    - echo "docker-compose 실행 성공"
    - IMAGE_ID=$(docker images -q aurasphere-backend_server:latest)
    - >
      if [ -z "$IMAGE_ID" ]; then
        echo "Error: Image aurasphere-backend_server:latest not found";
        exit 1;
      fi
    - docker tag aurasphere-backend_server:latest "$DOCKER_HUB_NAME/aurasphere-server:latest"
    - docker push "$DOCKER_HUB_NAME/aurasphere-server:latest"
    - echo "이미지 푸시 성공"
  after_script:
    - docker logout
  only:
    - feature/notification
  tags:
    - package

deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375", "--insecure-registry=0.0.0.0/0"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - deploy
  before_script:
    - echo [INFO] docker deploy start!
    - if [ -z "$DOCKER_HUB_NAME" ] || [ -z "$DOCKER_HUB_PW" ]; then echo "Docker Hub credentials are missing"; exit 1; fi
    - echo "$DOCKER_HUB_PW" | docker login --username "$DOCKER_HUB_NAME" --password-stdin
    - echo "Docker Hub 로그인 성공"
  script:
    - echo "배포 서버로 SSH 연결하여 배포 시작"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
    - |
      ssh -i ~/.ssh/id_rsa $REMOTE_USER@$REMOTE_HOST <<EOF
      cd ~/distribute-test/
      docker-compose down
      docker-compose pull
      docker-compose up -d
      docker-compose ps
      docker-compose logs
      EOF
  after_script:
    - docker logout
    - echo [INFO] docker deploy end!
  only:
    - feature/notification

