stages:
  - test
  - deploy

test_job:
  stage: test
  script:
    - echo "Building and testing application..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t aurasphere-backend-server:latest .
    - docker tag aurasphere-backend-server:latest seungilbaek/aurasphere-server:latest
    - docker push seungilbaek/aurasphere-server:latest
    - echo "Build and test completed successfully."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d
