version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aurasphere-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aurasphere
      MYSQL_USER: elice-user
      MYSQL_PASSWORD: Qwer1234!@
    ports:
      - "3307:3306"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "elice-user", "-pQwer1234!@"]
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: aurasphere-backend-server:latest
    container_name: aurasphere-backend-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATASOURCE_URL: jdbc:mysql://aurasphere-backend-mysql:3306/aurasphere
      DB_USERNAME: elice-user
      DB_PASSWORD: Qwer1234!@
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:latest
    container_name: aurasphere-backend-nginx
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge
